# ~/.config/hypr/hyprpaper.conf
preload = /home/juan_sebastian/Downloads/fondos/fondo2.jpg
preload = /home/juan_sebastian/Downloads/fondos/fondo3.png
preload = /home/juan_sebastian/Downloads/fondos/got.jpg
preload = /home/juan_sebastian/Downloads/fondos/pas.jpg
preload = /home/juan_sebastian/Downloads/fondos/s.png
preload = /home/juan_sebastian/Downloads/fondos/arch.png
preload = /home/juan_sebastian/Downloads/fondos/vaca.jpg
wallpaper = , /home/juan_sebastian/Downloads/fondos/fondo2jpg/fondo3.png/got.jpg/pas.jpg/s.png/arch.png/vaca.jpg
